[package]
name = "rustpert"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = { version = "0.2.19" }
rug = { version = "1.27.0", features = ["num-traits"]}
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
